In [7]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize

#spilloverを考慮したSCM感度分析
"""
この感度分析の目的は、「ドナー群（比較対象）に介入の波及効果があるときに、SCMの推定精度がどれほど悪化するか」を確認すること。
SCMの計算結果は「処置群の実績値」と「合成コントロール（反実仮想）の予測値」の差分（Gap）の平均値。
そのため商圏が重複する対照群への流出によって処置群の数値が減っているかどうかに関わらず、
「ドナー側の来訪者が増えてしまうこと自体が分析の敵（処置効果の過小評価につながってしまう）」であるため、
まずは介入によるドナー側の増加（汚染）のみをシンプルにシミュレーションする
"""
input_path = Path("/content/drive/MyDrive/因果推論/h3_mesh_panel.csv")
output_dir = input_path.parent

intervention_date = pd.Timestamp("2025-01-01")
#介入の影響が処置を受けていない周辺地域（ドナーユニット）にどれくらいの強さで波及すると仮定するかを示すパラメータ
spillover_strengths = [0.00, 0.25, 0.50, 1.00]
#処置エリアとの商圏重複率（overlap_score）がこの値以上であるドナーユニットを、分析から除外するためのしきい値
#スピルオーバーの影響を受けている可能性が高いドナー（対照群）を、分析から除外するためのしきい値
exclusion_thresholds = [1.01, 0.70, 0.60, 0.50, 0.30]

#このCSVには実測の距離・隣接関係・商圏重複率がないため、教材用にdonor_groupとJaccard係数を設定する。駅名や実地域は表さない。
teaching_groups = {
    "donor_group_1": {"h3_ids": [f"h3_mesh_{i:02d}" for i in range(7, 13)], "overlap_score": 0.75},
    "donor_group_2": {"h3_ids": [f"h3_mesh_{i:02d}" for i in range(13, 19)], "overlap_score": 0.45},
    "donor_group_3": {"h3_ids": [f"h3_mesh_{i:02d}" for i in range(19, 25)], "overlap_score": 0.25},
    "donor_group_4": {"h3_ids": [f"h3_mesh_{i:02d}" for i in range(25, 31)], "overlap_score": 0.20},
    "donor_group_5": {"h3_ids": [f"h3_mesh_{i:02d}" for i in range(31, 37)], "overlap_score": 0.65},
}
display(teaching_groups)

def rmspe(values):
    values = np.asarray(values, dtype=float)
    return float(np.sqrt(np.mean(values ** 2)))

#spillover_strengths と exclusion_thresholds のすべての組み合わせ、つまり各シナリオに対して
#合成コントロール法の計算を行い、その結果を返すfit_scm()関数を定義
def fit_scm(panel, strength, threshold, true_effect):
    work = panel.copy()
    #work["assumed_spillover"] :仮定された波及効果によるドナーユニットの来訪者数の「かさ上げ分」を人工的に作り出した値。
    work["assumed_spillover"] = np.where((work["treated"] == 0) & (work["date"] >= intervention_date),
        #商圏重複率 * 未処置の領域に波及して影響を仮定した効果 * 真の処置効果
        work["overlap_score"] * strength * true_effect,0.0)
    #work["visitors_scenario"] はドナー群に波及効果の増加分を踏まえた観測者数
    work["visitors_scenario"] = work["visitors"] + work["assumed_spillover"]
    #対照群のうち、商圏重複率が特定のしきい値以上であるドナーグループを特定し、それらを分析から除外するリストを作成する
    excluded_groups = sorted(
        work.loc[(work["treated"] == 0) & (work["overlap_score"] >= threshold),"donor_group"
        ].dropna().unique())
    #商圏重複率のしきい値を変えて、商圏重複率が大きいエリアを段階的に除外してみる。
    donor_part = work.loc[(work["treated"] == 0) & (work["overlap_score"] < threshold)]
    donor_ids = sorted(donor_part["h3_id"].unique())
    if not donor_ids:
        raise ValueError(f"threshold={threshold}ではドナーが0件です。")
    #処置系列を作成
    actual = work.loc[work["treated"] == 1].groupby("date")["visitors_scenario"].mean().sort_index()
    #商圏重複率の閾値を超えたメッシュ除外後のドナー系列を作成
    donor_wide = (
        donor_part.pivot(index="date", columns="h3_id", values="visitors_scenario")
        .sort_index().loc[:, donor_ids]
    )
    dates = actual.index.intersection(donor_wide.index)
    actual = actual.loc[dates]
    donor_wide = donor_wide.loc[dates]
    pre_mask = dates < intervention_date
    #pre_mask のブール値を反転させたもの（論理否定)
    post_mask = ~pre_mask
    y_pre = actual.loc[pre_mask].to_numpy(float)
    x_pre = donor_wide.loc[pre_mask].to_numpy(float)

    def objective(weights):
        residual = y_pre - x_pre @ weights
        return np.mean(residual ** 2) / np.var(y_pre)

    donor_count = len(donor_ids)
    result = minimize(
        objective,
        np.full(donor_count, 1.0 / donor_count),
        method="SLSQP",
        bounds=[(0.0, 1.0)] * donor_count,
        constraints={"type": "eq", "fun": lambda w: np.sum(w) - 1.0},
        options={"ftol": 1e-12, "maxiter": 5000, "disp": False}
    )
    if not result.success:
        raise RuntimeError(f"SCM最適化失敗: {result.message}")

    weights = result.x
    synthetic = donor_wide.to_numpy(float) @ weights
    series = pd.DataFrame({
        "date": dates,
        "actual_treated_area": actual.to_numpy(float),
        "synthetic_treated_area": synthetic
    })
    series["gap"] = series["actual_treated_area"] - series["synthetic_treated_area"]
    series["period"] = np.where(series["date"] < intervention_date, "pre", "post")
    pre_gap = series.loc[series["period"] == "pre", "gap"]
    post_gap = series.loc[series["period"] == "post", "gap"]
    pre_rmspe = rmspe(pre_gap)
    post_rmspe = rmspe(post_gap)
    scenario_id = f"strength_{strength:.2f}__threshold_{threshold:.2f}"
    series["scenario_id"] = scenario_id
    display(series)

    summary = {
        "scenario_id": scenario_id,
        "spillover_strength": strength,
        "exclusion_threshold": threshold,
        "excluded_groups": "|".join(excluded_groups) if excluded_groups else "none",
        "donor_mesh_count": donor_count,
        "pre_rmspe": pre_rmspe,
        "post_rmspe": post_rmspe,
        "post_pre_rmspe_ratio": post_rmspe / pre_rmspe,
        "mean_post_gap": float(post_gap.mean()),
        "true_direct_effect": true_effect,
        "estimation_error": float(post_gap.mean() - true_effect),
    }
    weights_df = pd.DataFrame({
        "scenario_id": scenario_id,
        "donor_h3_id": donor_ids,
        "weight": weights
    })
    display(weights_df)
    return summary, series, weights_df

#データの読み込み・データの確認
df = pd.read_csv(input_path, parse_dates=["date"])
#必要列が読み込んだデータフレームに揃っているかを確認
required = {"date", "h3_id", "visitors", "treated", "post", "treatment_effect_true"}
missing = required - set(df.columns)
if missing:
    raise ValueError(f"必要列がありません: {sorted(missing)}")

#データ型を指定
df["h3_id"] = df["h3_id"].astype(str)
df["visitors"] = pd.to_numeric(df["visitors"], errors="raise")
df["treated"] = pd.to_numeric(df["treated"], errors="raise").astype(int)
df["post"] = pd.to_numeric(df["post"], errors="raise").astype(int)
df["treatment_effect_true"] = pd.to_numeric(df["treatment_effect_true"], errors="raise")

#重複している行がないか確認
if df.duplicated(["date", "h3_id"]).any():
    raise ValueError("date × h3_idに重複があります。")
#欠損値がないか確認
if df.isna().any().any():
    raise ValueError("欠損値があります。")
#適切にデータが揃っているか確認（※2024年はうるう年であり、366日存在）
date_counts = df.groupby("h3_id")["date"].nunique()
display(date_counts)
#date_counts Seriesに含まれるユニークな値の数を数えています。
#date_counts Seriesは、各h3_idが持っているユニークな日付の数を値として持っています
if date_counts.nunique() != 1 or date_counts.iloc[0] != df["date"].nunique():
    raise ValueError("バランスパネルではありません。")
#post列が介入日に対し正しく反映されているかを確認
expected_post = (df["date"] >= intervention_date).astype(int)
display(expected_post)
if not np.array_equal(df["post"].to_numpy(), expected_post.to_numpy()):
    raise ValueError("post列と介入日の定義が一致しません。")
#処置群を表すtreatedが1になっているか（0を含んでいないか）確認
if df.groupby("h3_id")["treated"].nunique().max() != 1:
    raise ValueError("同じh3_id内でtreatedが変化しています。")
#処置群のメッシュの集合を作成
treated_ids = set(df.loc[df["treated"] == 1, "h3_id"].unique())
#対照群のメッシュの集合を作成
control_ids = set(df.loc[df["treated"] == 0, "h3_id"].unique())
#teaching_groupsでドナー群として定義したh3_id のユニークな集合を作成
declared_ids = {h3_id for group in teaching_groups.values() for h3_id in group["h3_ids"]}
display(declared_ids)
if control_ids != declared_ids:
    raise ValueError(
        "CSVの対照h3_idと教材用グループ定義が一致しません。\n"
        f"CSVのみに存在: {sorted(control_ids - declared_ids)}\n"
        f"定義のみに存在: {sorted(declared_ids - control_ids)}"
    )
#処置群のメッシュがドナー群のメッシュに混入していないか確認
if treated_ids & declared_ids:
    raise ValueError("処置メッシュが教材用ドナー群へ混入しています。")

#メッシュに関するメタデータを結合
metadata_rows = []
for group_name, setting in teaching_groups.items():
    for h3_id in setting["h3_ids"]:
        metadata_rows.append({
            "h3_id": h3_id,
            "donor_group": group_name,
            "overlap_score": setting["overlap_score"],
            "score_status": "artificial_for_teaching_not_observed",
        })
metadata = pd.DataFrame(metadata_rows)
df = df.merge(metadata, on="h3_id", how="left", validate="many_to_one")
#結合によって生じた欠損を補完
df.loc[df["treated"] == 1, "donor_group"] = "treated_area"
df.loc[df["treated"] == 1, "overlap_score"] = 0.0
df.loc[df["treated"] == 1, "score_status"] = "not_applicable"
#true_effect の値が有効であることを保証し、後続の計算に進む前のエラーハンドリング
true_effect = float(
    df.loc[(df["treated"] == 1) & (df["post"] == 1), "treatment_effect_true"].mean()
)
if not np.isfinite(true_effect):
    raise ValueError("施策後の真の直接効果を取得できません。")

#全20シナリオを推定
summaries, series_list, weights_list = [], [], []
for strength in spillover_strengths:
    for threshold in exclusion_thresholds:
        summary, series, weights = fit_scm(df, strength, threshold, true_effect)
        summaries.append(summary)
        series_list.append(series)
        weights_list.append(weights)

summary_df = pd.DataFrame(summaries)
print(f"summary_df \n")
display(summary_df)
series_df = pd.concat(series_list, ignore_index=True)
print(f"series_df series_df : 20シナリオ * 731日（閏年含む）/シナリオ = 14620行　\n")
display(series_df)
weights_df = pd.concat(weights_list, ignore_index=True)
print(f"weights_df : 総行数は、20個の各シナリオで選ばれたドナーメッシュの数をすべて合計したもの\n")
display(weights_df)

#出力をCSVで保存
metadata.to_csv(output_dir / "teaching_spillover_metadata.csv", index=False)
summary_df.to_csv(output_dir / "spillover_sensitivity_summary.csv", index=False)
series_df.to_csv(output_dir / "spillover_sensitivity_series.csv", index=False)
weights_df.to_csv(output_dir / "spillover_sensitivity_weights.csv", index=False)

audit_df = pd.DataFrame([{
    "input_path": str(input_path),
    "date_min": df["date"].min(),
    "date_max": df["date"].max(),
    "date_count": df["date"].nunique(),
    "row_count": len(df),
    "mesh_count": df["h3_id"].nunique(),
    "treated_mesh_count": df.loc[df["treated"] == 1, "h3_id"].nunique(),
    "donor_mesh_count": df.loc[df["treated"] == 0, "h3_id"].nunique(),
    "duplicate_date_h3_count": int(df.duplicated(["date", "h3_id"]).sum()),
    "missing_value_count": int(df.isna().sum().sum()),
    "true_direct_effect": true_effect,
    "spillover_formula": "strength * artificial_overlap_score * true_effect"
}])
display(audit_df)
audit_df.to_csv(output_dir / "data_audit.csv", index=False)

{'donor_group_1': {'h3_ids': ['h3_mesh_07',
   'h3_mesh_08',
   'h3_mesh_09',
   'h3_mesh_10',
   'h3_mesh_11',
   'h3_mesh_12'],
  'overlap_score': 0.75},
 'donor_group_2': {'h3_ids': ['h3_mesh_13',
   'h3_mesh_14',
   'h3_mesh_15',
   'h3_mesh_16',
   'h3_mesh_17',
   'h3_mesh_18'],
  'overlap_score': 0.45},
 'donor_group_3': {'h3_ids': ['h3_mesh_19',
   'h3_mesh_20',
   'h3_mesh_21',
   'h3_mesh_22',
   'h3_mesh_23',
   'h3_mesh_24'],
  'overlap_score': 0.25},
 'donor_group_4': {'h3_ids': ['h3_mesh_25',
   'h3_mesh_26',
   'h3_mesh_27',
   'h3_mesh_28',
   'h3_mesh_29',
   'h3_mesh_30'],
  'overlap_score': 0.2},
 'donor_group_5': {'h3_ids': ['h3_mesh_31',
   'h3_mesh_32',
   'h3_mesh_33',
   'h3_mesh_34',
   'h3_mesh_35',
   'h3_mesh_36'],
  'overlap_score': 0.65}}

h3_id
h3_mesh_01    731
h3_mesh_02    731
h3_mesh_03    731
h3_mesh_04    731
h3_mesh_05    731
h3_mesh_06    731
h3_mesh_07    731
h3_mesh_08    731
h3_mesh_09    731
h3_mesh_10    731
h3_mesh_11    731
h3_mesh_12    731
h3_mesh_13    731
h3_mesh_14    731
h3_mesh_15    731
h3_mesh_16    731
h3_mesh_17    731
h3_mesh_18    731
h3_mesh_19    731
h3_mesh_20    731
h3_mesh_21    731
h3_mesh_22    731
h3_mesh_23    731
h3_mesh_24    731
h3_mesh_25    731
h3_mesh_26    731
h3_mesh_27    731
h3_mesh_28    731
h3_mesh_29    731
h3_mesh_30    731
h3_mesh_31    731
h3_mesh_32    731
h3_mesh_33    731
h3_mesh_34    731
h3_mesh_35    731
h3_mesh_36    731
Name: date, dtype: int64

0        0
1        0
2        0
3        0
4        0
        ..
26311    1
26312    1
26313    1
26314    1
26315    1
Name: date, Length: 26316, dtype: int64

{'h3_mesh_07',
 'h3_mesh_08',
 'h3_mesh_09',
 'h3_mesh_10',
 'h3_mesh_11',
 'h3_mesh_12',
 'h3_mesh_13',
 'h3_mesh_14',
 'h3_mesh_15',
 'h3_mesh_16',
 'h3_mesh_17',
 'h3_mesh_18',
 'h3_mesh_19',
 'h3_mesh_20',
 'h3_mesh_21',
 'h3_mesh_22',
 'h3_mesh_23',
 'h3_mesh_24',
 'h3_mesh_25',
 'h3_mesh_26',
 'h3_mesh_27',
 'h3_mesh_28',
 'h3_mesh_29',
 'h3_mesh_30',
 'h3_mesh_31',
 'h3_mesh_32',
 'h3_mesh_33',
 'h3_mesh_34',
 'h3_mesh_35',
 'h3_mesh_36'}

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1274.327739,-5.295380,pre,strength_0.00__threshold_1.01
1,2024-01-02,1289.206883,1286.982157,2.224727,pre,strength_0.00__threshold_1.01
2,2024-01-03,1305.904895,1298.944127,6.960768,pre,strength_0.00__threshold_1.01
3,2024-01-04,1316.002988,1310.357281,5.645707,pre,strength_0.00__threshold_1.01
4,2024-01-05,1338.300240,1323.250608,15.049632,pre,strength_0.00__threshold_1.01
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1398.428329,223.306623,post,strength_0.00__threshold_1.01
727,2025-12-28,1613.795981,1385.643640,228.152341,post,strength_0.00__threshold_1.01
728,2025-12-29,1541.604173,1326.986701,214.617472,post,strength_0.00__threshold_1.01
729,2025-12-30,1560.426800,1341.274830,219.151971,post,strength_0.00__threshold_1.01
730,2025-12-31,1570.726416,1341.280260,229.446155,post,strength_0.00__threshold_1.01

                      scenario_id donor_h3_id        weight
0   strength_0.00__threshold_1.01  h3_mesh_07  3.259500e-02
1   strength_0.00__threshold_1.01  h3_mesh_08  8.682807e-02
2   strength_0.00__threshold_1.01  h3_mesh_09  8.343769e-02
3   strength_0.00__threshold_1.01  h3_mesh_10  1.143291e-01
4   strength_0.00__threshold_1.01  h3_mesh_11  1.219556e-21
5   strength_0.00__threshold_1.01  h3_mesh_12  2.560679e-02
6   strength_0.00__threshold_1.01  h3_mesh_13  2.162857e-03
7   strength_0.00__threshold_1.01  h3_mesh_14  4.670705e-19
8   strength_0.00__threshold_1.01  h3_mesh_15  1.579440e-02
9   strength_0.00__threshold_1.01  h3_mesh_16  1.809885e-18
10  strength_0.00__threshold_1.01  h3_mesh_17  2.309727e-02
11  strength_0.00__threshold_1.01  h3_mesh_18  2.180228e-02
12  strength_0.00__threshold_1.01  h3_mesh_19  4.629121e-02
13  strength_0.00__threshold_1.01  h3_mesh_20  0.000000e+00
14  strength_0.00__threshold_1.01  h3_mesh_21  3.576652e-02
15  strength_0.00__threshold_1.01  h3_mesh_22  2.549932e-02
16  strength_0.00__threshold_1.01  h3_mesh_23  7.664013e-03
17  strength_0.00__threshold_1.01  h3_mesh_24  2.174793e-03
18  strength_0.00__threshold_1.01  h3_mesh_25  3.626964e-02
19  strength_0.00__threshold_1.01  h3_mesh_26  3.730636e-02
20  strength_0.00__threshold_1.01  h3_mesh_27  2.962244e-02
21  strength_0.00__threshold_1.01  h3_mesh_28  6.193040e-02
22  strength_0.00__threshold_1.01  h3_mesh_29  4.549510e-02
23  strength_0.00__threshold_1.01  h3_mesh_30  1.299194e-02
24  strength_0.00__threshold_1.01  h3_mesh_31  2.318221e-02
25  strength_0.00__threshold_1.01  h3_mesh_32  4.060352e-02
26  strength_0.00__threshold_1.01  h3_mesh_33  4.943965e-02
27  strength_0.00__threshold_1.01  h3_mesh_34  7.583486e-02
28  strength_0.00__threshold_1.01  h3_mesh_35  4.278780e-02
29  strength_0.00__threshold_1.01  h3_mesh_36  2.148679e-02

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1273.595992,-4.563633,pre,strength_0.00__threshold_0.70
1,2024-01-02,1289.206883,1285.105770,4.101113,pre,strength_0.00__threshold_0.70
2,2024-01-03,1305.904895,1296.184020,9.720876,pre,strength_0.00__threshold_0.70
3,2024-01-04,1316.002988,1304.821048,11.181939,pre,strength_0.00__threshold_0.70
4,2024-01-05,1338.300240,1320.194714,18.105526,pre,strength_0.00__threshold_0.70
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1401.590457,220.144495,post,strength_0.00__threshold_0.70
727,2025-12-28,1613.795981,1387.028218,226.767764,post,strength_0.00__threshold_0.70
728,2025-12-29,1541.604173,1327.743880,213.860293,post,strength_0.00__threshold_0.70
729,2025-12-30,1560.426800,1337.672770,222.754030,post,strength_0.00__threshold_0.70
730,2025-12-31,1570.726416,1345.421908,225.304507,post,strength_0.00__threshold_0.70

                      scenario_id donor_h3_id        weight
0   strength_0.00__threshold_0.70  h3_mesh_13  1.469560e-02
1   strength_0.00__threshold_0.70  h3_mesh_14  1.258508e-02
2   strength_0.00__threshold_0.70  h3_mesh_15  0.000000e+00
3   strength_0.00__threshold_0.70  h3_mesh_16  8.951726e-19
4   strength_0.00__threshold_0.70  h3_mesh_17  2.885077e-02
5   strength_0.00__threshold_0.70  h3_mesh_18  4.172011e-02
6   strength_0.00__threshold_0.70  h3_mesh_19  5.547472e-02
7   strength_0.00__threshold_0.70  h3_mesh_20  0.000000e+00
8   strength_0.00__threshold_0.70  h3_mesh_21  4.827261e-02
9   strength_0.00__threshold_0.70  h3_mesh_22  2.805422e-02
10  strength_0.00__threshold_0.70  h3_mesh_23  0.000000e+00
11  strength_0.00__threshold_0.70  h3_mesh_24  3.765360e-02
12  strength_0.00__threshold_0.70  h3_mesh_25  5.313692e-02
13  strength_0.00__threshold_0.70  h3_mesh_26  6.595899e-02
14  strength_0.00__threshold_0.70  h3_mesh_27  6.764886e-02
15  strength_0.00__threshold_0.70  h3_mesh_28  5.871389e-02
16  strength_0.00__threshold_0.70  h3_mesh_29  6.206895e-02
17  strength_0.00__threshold_0.70  h3_mesh_30  2.036424e-02
18  strength_0.00__threshold_0.70  h3_mesh_31  2.158219e-02
19  strength_0.00__threshold_0.70  h3_mesh_32  7.703022e-02
20  strength_0.00__threshold_0.70  h3_mesh_33  8.204537e-02
21  strength_0.00__threshold_0.70  h3_mesh_34  1.156156e-01
22  strength_0.00__threshold_0.70  h3_mesh_35  7.048754e-02
23  strength_0.00__threshold_0.70  h3_mesh_36  3.804049e-02

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1257.680963,11.351396,pre,strength_0.00__threshold_0.60
1,2024-01-02,1289.206883,1273.919311,15.287572,pre,strength_0.00__threshold_0.60
2,2024-01-03,1305.904895,1284.310272,21.594623,pre,strength_0.00__threshold_0.60
3,2024-01-04,1316.002988,1292.264617,23.738371,pre,strength_0.00__threshold_0.60
4,2024-01-05,1338.300240,1313.713389,24.586851,pre,strength_0.00__threshold_0.60
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1405.368290,216.366663,post,strength_0.00__threshold_0.60
727,2025-12-28,1613.795981,1387.991100,225.804881,post,strength_0.00__threshold_0.60
728,2025-12-29,1541.604173,1322.127100,219.477074,post,strength_0.00__threshold_0.60
729,2025-12-30,1560.426800,1340.128795,220.298005,post,strength_0.00__threshold_0.60
730,2025-12-31,1570.726416,1351.159884,219.566532,post,strength_0.00__threshold_0.60

                      scenario_id donor_h3_id        weight
0   strength_0.00__threshold_0.60  h3_mesh_13  4.298166e-17
1   strength_0.00__threshold_0.60  h3_mesh_14  3.147474e-02
2   strength_0.00__threshold_0.60  h3_mesh_15  0.000000e+00
3   strength_0.00__threshold_0.60  h3_mesh_16  3.967489e-18
4   strength_0.00__threshold_0.60  h3_mesh_17  4.888014e-02
5   strength_0.00__threshold_0.60  h3_mesh_18  1.384824e-01
6   strength_0.00__threshold_0.60  h3_mesh_19  1.206815e-01
7   strength_0.00__threshold_0.60  h3_mesh_20  1.578800e-18
8   strength_0.00__threshold_0.60  h3_mesh_21  1.894217e-02
9   strength_0.00__threshold_0.60  h3_mesh_22  1.402154e-02
10  strength_0.00__threshold_0.60  h3_mesh_23  0.000000e+00
11  strength_0.00__threshold_0.60  h3_mesh_24  1.065348e-02
12  strength_0.00__threshold_0.60  h3_mesh_25  3.572069e-02
13  strength_0.00__threshold_0.60  h3_mesh_26  4.118500e-02
14  strength_0.00__threshold_0.60  h3_mesh_27  1.775281e-01
15  strength_0.00__threshold_0.60  h3_mesh_28  2.315846e-17
16  strength_0.00__threshold_0.60  h3_mesh_29  2.121972e-01
17  strength_0.00__threshold_0.60  h3_mesh_30  1.502330e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1257.680963,11.351396,pre,strength_0.00__threshold_0.50
1,2024-01-02,1289.206883,1273.919311,15.287572,pre,strength_0.00__threshold_0.50
2,2024-01-03,1305.904895,1284.310272,21.594623,pre,strength_0.00__threshold_0.50
3,2024-01-04,1316.002988,1292.264617,23.738371,pre,strength_0.00__threshold_0.50
4,2024-01-05,1338.300240,1313.713389,24.586851,pre,strength_0.00__threshold_0.50
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1405.368290,216.366663,post,strength_0.00__threshold_0.50
727,2025-12-28,1613.795981,1387.991100,225.804881,post,strength_0.00__threshold_0.50
728,2025-12-29,1541.604173,1322.127100,219.477074,post,strength_0.00__threshold_0.50
729,2025-12-30,1560.426800,1340.128795,220.298005,post,strength_0.00__threshold_0.50
730,2025-12-31,1570.726416,1351.159884,219.566532,post,strength_0.00__threshold_0.50

                      scenario_id donor_h3_id        weight
0   strength_0.00__threshold_0.50  h3_mesh_13  4.298166e-17
1   strength_0.00__threshold_0.50  h3_mesh_14  3.147474e-02
2   strength_0.00__threshold_0.50  h3_mesh_15  0.000000e+00
3   strength_0.00__threshold_0.50  h3_mesh_16  3.967489e-18
4   strength_0.00__threshold_0.50  h3_mesh_17  4.888014e-02
5   strength_0.00__threshold_0.50  h3_mesh_18  1.384824e-01
6   strength_0.00__threshold_0.50  h3_mesh_19  1.206815e-01
7   strength_0.00__threshold_0.50  h3_mesh_20  1.578800e-18
8   strength_0.00__threshold_0.50  h3_mesh_21  1.894217e-02
9   strength_0.00__threshold_0.50  h3_mesh_22  1.402154e-02
10  strength_0.00__threshold_0.50  h3_mesh_23  0.000000e+00
11  strength_0.00__threshold_0.50  h3_mesh_24  1.065348e-02
12  strength_0.00__threshold_0.50  h3_mesh_25  3.572069e-02
13  strength_0.00__threshold_0.50  h3_mesh_26  4.118500e-02
14  strength_0.00__threshold_0.50  h3_mesh_27  1.775281e-01
15  strength_0.00__threshold_0.50  h3_mesh_28  2.315846e-17
16  strength_0.00__threshold_0.50  h3_mesh_29  2.121972e-01
17  strength_0.00__threshold_0.50  h3_mesh_30  1.502330e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1259.251455,9.780904,pre,strength_0.00__threshold_0.30
1,2024-01-02,1289.206883,1280.143575,9.063309,pre,strength_0.00__threshold_0.30
2,2024-01-03,1305.904895,1291.511263,14.393632,pre,strength_0.00__threshold_0.30
3,2024-01-04,1316.002988,1299.250608,16.752380,pre,strength_0.00__threshold_0.30
4,2024-01-05,1338.300240,1321.748798,16.551442,pre,strength_0.00__threshold_0.30
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1408.101317,213.633636,post,strength_0.00__threshold_0.30
727,2025-12-28,1613.795981,1390.540891,223.255090,post,strength_0.00__threshold_0.30
728,2025-12-29,1541.604173,1324.097489,217.506685,post,strength_0.00__threshold_0.30
729,2025-12-30,1560.426800,1340.990828,219.435972,post,strength_0.00__threshold_0.30
730,2025-12-31,1570.726416,1347.659088,223.067328,post,strength_0.00__threshold_0.30

                      scenario_id donor_h3_id        weight
0   strength_0.00__threshold_0.30  h3_mesh_19  1.290707e-01
1   strength_0.00__threshold_0.30  h3_mesh_20  0.000000e+00
2   strength_0.00__threshold_0.30  h3_mesh_21  2.732731e-02
3   strength_0.00__threshold_0.30  h3_mesh_22  1.512740e-02
4   strength_0.00__threshold_0.30  h3_mesh_23  1.430850e-17
5   strength_0.00__threshold_0.30  h3_mesh_24  4.357521e-02
6   strength_0.00__threshold_0.30  h3_mesh_25  4.312686e-02
7   strength_0.00__threshold_0.30  h3_mesh_26  4.343876e-02
8   strength_0.00__threshold_0.30  h3_mesh_27  2.388176e-01
9   strength_0.00__threshold_0.30  h3_mesh_28  0.000000e+00
10  strength_0.00__threshold_0.30  h3_mesh_29  2.579806e-01
11  strength_0.00__threshold_0.30  h3_mesh_30  2.015356e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1274.327739,-5.295380,pre,strength_0.25__threshold_1.01
1,2024-01-02,1289.206883,1286.982157,2.224727,pre,strength_0.25__threshold_1.01
2,2024-01-03,1305.904895,1298.944127,6.960768,pre,strength_0.25__threshold_1.01
3,2024-01-04,1316.002988,1310.357281,5.645707,pre,strength_0.25__threshold_1.01
4,2024-01-05,1338.300240,1323.250608,15.049632,pre,strength_0.25__threshold_1.01
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1427.255084,194.479868,post,strength_0.25__threshold_1.01
727,2025-12-28,1613.795981,1414.470395,199.325586,post,strength_0.25__threshold_1.01
728,2025-12-29,1541.604173,1355.813456,185.790717,post,strength_0.25__threshold_1.01
729,2025-12-30,1560.426800,1370.101585,190.325215,post,strength_0.25__threshold_1.01
730,2025-12-31,1570.726416,1370.107016,200.619400,post,strength_0.25__threshold_1.01

                      scenario_id donor_h3_id        weight
0   strength_0.25__threshold_1.01  h3_mesh_07  3.259500e-02
1   strength_0.25__threshold_1.01  h3_mesh_08  8.682807e-02
2   strength_0.25__threshold_1.01  h3_mesh_09  8.343769e-02
3   strength_0.25__threshold_1.01  h3_mesh_10  1.143291e-01
4   strength_0.25__threshold_1.01  h3_mesh_11  1.219556e-21
5   strength_0.25__threshold_1.01  h3_mesh_12  2.560679e-02
6   strength_0.25__threshold_1.01  h3_mesh_13  2.162857e-03
7   strength_0.25__threshold_1.01  h3_mesh_14  4.670705e-19
8   strength_0.25__threshold_1.01  h3_mesh_15  1.579440e-02
9   strength_0.25__threshold_1.01  h3_mesh_16  1.809885e-18
10  strength_0.25__threshold_1.01  h3_mesh_17  2.309727e-02
11  strength_0.25__threshold_1.01  h3_mesh_18  2.180228e-02
12  strength_0.25__threshold_1.01  h3_mesh_19  4.629121e-02
13  strength_0.25__threshold_1.01  h3_mesh_20  0.000000e+00
14  strength_0.25__threshold_1.01  h3_mesh_21  3.576652e-02
15  strength_0.25__threshold_1.01  h3_mesh_22  2.549932e-02
16  strength_0.25__threshold_1.01  h3_mesh_23  7.664013e-03
17  strength_0.25__threshold_1.01  h3_mesh_24  2.174793e-03
18  strength_0.25__threshold_1.01  h3_mesh_25  3.626964e-02
19  strength_0.25__threshold_1.01  h3_mesh_26  3.730636e-02
20  strength_0.25__threshold_1.01  h3_mesh_27  2.962244e-02
21  strength_0.25__threshold_1.01  h3_mesh_28  6.193040e-02
22  strength_0.25__threshold_1.01  h3_mesh_29  4.549510e-02
23  strength_0.25__threshold_1.01  h3_mesh_30  1.299194e-02
24  strength_0.25__threshold_1.01  h3_mesh_31  2.318221e-02
25  strength_0.25__threshold_1.01  h3_mesh_32  4.060352e-02
26  strength_0.25__threshold_1.01  h3_mesh_33  4.943965e-02
27  strength_0.25__threshold_1.01  h3_mesh_34  7.583486e-02
28  strength_0.25__threshold_1.01  h3_mesh_35  4.278780e-02
29  strength_0.25__threshold_1.01  h3_mesh_36  2.148679e-02

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1273.595992,-4.563633,pre,strength_0.25__threshold_0.70
1,2024-01-02,1289.206883,1285.105770,4.101113,pre,strength_0.25__threshold_0.70
2,2024-01-03,1305.904895,1296.184020,9.720876,pre,strength_0.25__threshold_0.70
3,2024-01-04,1316.002988,1304.821048,11.181939,pre,strength_0.25__threshold_0.70
4,2024-01-05,1338.300240,1320.194714,18.105526,pre,strength_0.25__threshold_0.70
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1424.420754,197.314199,post,strength_0.25__threshold_0.70
727,2025-12-28,1613.795981,1409.858514,203.937467,post,strength_0.25__threshold_0.70
728,2025-12-29,1541.604173,1350.574177,191.029996,post,strength_0.25__threshold_0.70
729,2025-12-30,1560.426800,1360.503067,199.923733,post,strength_0.25__threshold_0.70
730,2025-12-31,1570.726416,1368.252205,202.474211,post,strength_0.25__threshold_0.70

                      scenario_id donor_h3_id        weight
0   strength_0.25__threshold_0.70  h3_mesh_13  1.469560e-02
1   strength_0.25__threshold_0.70  h3_mesh_14  1.258508e-02
2   strength_0.25__threshold_0.70  h3_mesh_15  0.000000e+00
3   strength_0.25__threshold_0.70  h3_mesh_16  8.951726e-19
4   strength_0.25__threshold_0.70  h3_mesh_17  2.885077e-02
5   strength_0.25__threshold_0.70  h3_mesh_18  4.172011e-02
6   strength_0.25__threshold_0.70  h3_mesh_19  5.547472e-02
7   strength_0.25__threshold_0.70  h3_mesh_20  0.000000e+00
8   strength_0.25__threshold_0.70  h3_mesh_21  4.827261e-02
9   strength_0.25__threshold_0.70  h3_mesh_22  2.805422e-02
10  strength_0.25__threshold_0.70  h3_mesh_23  0.000000e+00
11  strength_0.25__threshold_0.70  h3_mesh_24  3.765360e-02
12  strength_0.25__threshold_0.70  h3_mesh_25  5.313692e-02
13  strength_0.25__threshold_0.70  h3_mesh_26  6.595899e-02
14  strength_0.25__threshold_0.70  h3_mesh_27  6.764886e-02
15  strength_0.25__threshold_0.70  h3_mesh_28  5.871389e-02
16  strength_0.25__threshold_0.70  h3_mesh_29  6.206895e-02
17  strength_0.25__threshold_0.70  h3_mesh_30  2.036424e-02
18  strength_0.25__threshold_0.70  h3_mesh_31  2.158219e-02
19  strength_0.25__threshold_0.70  h3_mesh_32  7.703022e-02
20  strength_0.25__threshold_0.70  h3_mesh_33  8.204537e-02
21  strength_0.25__threshold_0.70  h3_mesh_34  1.156156e-01
22  strength_0.25__threshold_0.70  h3_mesh_35  7.048754e-02
23  strength_0.25__threshold_0.70  h3_mesh_36  3.804049e-02

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1257.680963,11.351396,pre,strength_0.25__threshold_0.60
1,2024-01-02,1289.206883,1273.919311,15.287572,pre,strength_0.25__threshold_0.60
2,2024-01-03,1305.904895,1284.310272,21.594623,pre,strength_0.25__threshold_0.60
3,2024-01-04,1316.002988,1292.264617,23.738371,pre,strength_0.25__threshold_0.60
4,2024-01-05,1338.300240,1313.713389,24.586851,pre,strength_0.25__threshold_0.60
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1419.829124,201.905828,post,strength_0.25__threshold_0.60
727,2025-12-28,1613.795981,1402.451934,211.344047,post,strength_0.25__threshold_0.60
728,2025-12-29,1541.604173,1336.587934,205.016240,post,strength_0.25__threshold_0.60
729,2025-12-30,1560.426800,1354.589630,205.837171,post,strength_0.25__threshold_0.60
730,2025-12-31,1570.726416,1365.620718,205.105698,post,strength_0.25__threshold_0.60

                      scenario_id donor_h3_id        weight
0   strength_0.25__threshold_0.60  h3_mesh_13  4.298166e-17
1   strength_0.25__threshold_0.60  h3_mesh_14  3.147474e-02
2   strength_0.25__threshold_0.60  h3_mesh_15  0.000000e+00
3   strength_0.25__threshold_0.60  h3_mesh_16  3.967489e-18
4   strength_0.25__threshold_0.60  h3_mesh_17  4.888014e-02
5   strength_0.25__threshold_0.60  h3_mesh_18  1.384824e-01
6   strength_0.25__threshold_0.60  h3_mesh_19  1.206815e-01
7   strength_0.25__threshold_0.60  h3_mesh_20  1.578800e-18
8   strength_0.25__threshold_0.60  h3_mesh_21  1.894217e-02
9   strength_0.25__threshold_0.60  h3_mesh_22  1.402154e-02
10  strength_0.25__threshold_0.60  h3_mesh_23  0.000000e+00
11  strength_0.25__threshold_0.60  h3_mesh_24  1.065348e-02
12  strength_0.25__threshold_0.60  h3_mesh_25  3.572069e-02
13  strength_0.25__threshold_0.60  h3_mesh_26  4.118500e-02
14  strength_0.25__threshold_0.60  h3_mesh_27  1.775281e-01
15  strength_0.25__threshold_0.60  h3_mesh_28  2.315846e-17
16  strength_0.25__threshold_0.60  h3_mesh_29  2.121972e-01
17  strength_0.25__threshold_0.60  h3_mesh_30  1.502330e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1257.680963,11.351396,pre,strength_0.25__threshold_0.50
1,2024-01-02,1289.206883,1273.919311,15.287572,pre,strength_0.25__threshold_0.50
2,2024-01-03,1305.904895,1284.310272,21.594623,pre,strength_0.25__threshold_0.50
3,2024-01-04,1316.002988,1292.264617,23.738371,pre,strength_0.25__threshold_0.50
4,2024-01-05,1338.300240,1313.713389,24.586851,pre,strength_0.25__threshold_0.50
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1419.829124,201.905828,post,strength_0.25__threshold_0.50
727,2025-12-28,1613.795981,1402.451934,211.344047,post,strength_0.25__threshold_0.50
728,2025-12-29,1541.604173,1336.587934,205.016240,post,strength_0.25__threshold_0.50
729,2025-12-30,1560.426800,1354.589630,205.837171,post,strength_0.25__threshold_0.50
730,2025-12-31,1570.726416,1365.620718,205.105698,post,strength_0.25__threshold_0.50

                      scenario_id donor_h3_id        weight
0   strength_0.25__threshold_0.50  h3_mesh_13  4.298166e-17
1   strength_0.25__threshold_0.50  h3_mesh_14  3.147474e-02
2   strength_0.25__threshold_0.50  h3_mesh_15  0.000000e+00
3   strength_0.25__threshold_0.50  h3_mesh_16  3.967489e-18
4   strength_0.25__threshold_0.50  h3_mesh_17  4.888014e-02
5   strength_0.25__threshold_0.50  h3_mesh_18  1.384824e-01
6   strength_0.25__threshold_0.50  h3_mesh_19  1.206815e-01
7   strength_0.25__threshold_0.50  h3_mesh_20  1.578800e-18
8   strength_0.25__threshold_0.50  h3_mesh_21  1.894217e-02
9   strength_0.25__threshold_0.50  h3_mesh_22  1.402154e-02
10  strength_0.25__threshold_0.50  h3_mesh_23  0.000000e+00
11  strength_0.25__threshold_0.50  h3_mesh_24  1.065348e-02
12  strength_0.25__threshold_0.50  h3_mesh_25  3.572069e-02
13  strength_0.25__threshold_0.50  h3_mesh_26  4.118500e-02
14  strength_0.25__threshold_0.50  h3_mesh_27  1.775281e-01
15  strength_0.25__threshold_0.50  h3_mesh_28  2.315846e-17
16  strength_0.25__threshold_0.50  h3_mesh_29  2.121972e-01
17  strength_0.25__threshold_0.50  h3_mesh_30  1.502330e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1259.251455,9.780904,pre,strength_0.25__threshold_0.30
1,2024-01-02,1289.206883,1280.143575,9.063309,pre,strength_0.25__threshold_0.30
2,2024-01-03,1305.904895,1291.511263,14.393632,pre,strength_0.25__threshold_0.30
3,2024-01-04,1316.002988,1299.250608,16.752380,pre,strength_0.25__threshold_0.30
4,2024-01-05,1338.300240,1321.748798,16.551442,pre,strength_0.25__threshold_0.30
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1419.692843,202.042109,post,strength_0.25__threshold_0.30
727,2025-12-28,1613.795981,1402.132418,211.663563,post,strength_0.25__threshold_0.30
728,2025-12-29,1541.604173,1335.689015,205.915158,post,strength_0.25__threshold_0.30
729,2025-12-30,1560.426800,1352.582355,207.844446,post,strength_0.25__threshold_0.30
730,2025-12-31,1570.726416,1359.250615,211.475801,post,strength_0.25__threshold_0.30

                      scenario_id donor_h3_id        weight
0   strength_0.25__threshold_0.30  h3_mesh_19  1.290707e-01
1   strength_0.25__threshold_0.30  h3_mesh_20  0.000000e+00
2   strength_0.25__threshold_0.30  h3_mesh_21  2.732731e-02
3   strength_0.25__threshold_0.30  h3_mesh_22  1.512740e-02
4   strength_0.25__threshold_0.30  h3_mesh_23  1.430850e-17
5   strength_0.25__threshold_0.30  h3_mesh_24  4.357521e-02
6   strength_0.25__threshold_0.30  h3_mesh_25  4.312686e-02
7   strength_0.25__threshold_0.30  h3_mesh_26  4.343876e-02
8   strength_0.25__threshold_0.30  h3_mesh_27  2.388176e-01
9   strength_0.25__threshold_0.30  h3_mesh_28  0.000000e+00
10  strength_0.25__threshold_0.30  h3_mesh_29  2.579806e-01
11  strength_0.25__threshold_0.30  h3_mesh_30  2.015356e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1274.327739,-5.295380,pre,strength_0.50__threshold_1.01
1,2024-01-02,1289.206883,1286.982157,2.224727,pre,strength_0.50__threshold_1.01
2,2024-01-03,1305.904895,1298.944127,6.960768,pre,strength_0.50__threshold_1.01
3,2024-01-04,1316.002988,1310.357281,5.645707,pre,strength_0.50__threshold_1.01
4,2024-01-05,1338.300240,1323.250608,15.049632,pre,strength_0.50__threshold_1.01
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1456.081840,165.653113,post,strength_0.50__threshold_1.01
727,2025-12-28,1613.795981,1443.297151,170.498831,post,strength_0.50__threshold_1.01
728,2025-12-29,1541.604173,1384.640211,156.963962,post,strength_0.50__threshold_1.01
729,2025-12-30,1560.426800,1398.928340,161.498460,post,strength_0.50__threshold_1.01
730,2025-12-31,1570.726416,1398.933771,171.792645,post,strength_0.50__threshold_1.01

                      scenario_id donor_h3_id        weight
0   strength_0.50__threshold_1.01  h3_mesh_07  3.259500e-02
1   strength_0.50__threshold_1.01  h3_mesh_08  8.682807e-02
2   strength_0.50__threshold_1.01  h3_mesh_09  8.343769e-02
3   strength_0.50__threshold_1.01  h3_mesh_10  1.143291e-01
4   strength_0.50__threshold_1.01  h3_mesh_11  1.219556e-21
5   strength_0.50__threshold_1.01  h3_mesh_12  2.560679e-02
6   strength_0.50__threshold_1.01  h3_mesh_13  2.162857e-03
7   strength_0.50__threshold_1.01  h3_mesh_14  4.670705e-19
8   strength_0.50__threshold_1.01  h3_mesh_15  1.579440e-02
9   strength_0.50__threshold_1.01  h3_mesh_16  1.809885e-18
10  strength_0.50__threshold_1.01  h3_mesh_17  2.309727e-02
11  strength_0.50__threshold_1.01  h3_mesh_18  2.180228e-02
12  strength_0.50__threshold_1.01  h3_mesh_19  4.629121e-02
13  strength_0.50__threshold_1.01  h3_mesh_20  0.000000e+00
14  strength_0.50__threshold_1.01  h3_mesh_21  3.576652e-02
15  strength_0.50__threshold_1.01  h3_mesh_22  2.549932e-02
16  strength_0.50__threshold_1.01  h3_mesh_23  7.664013e-03
17  strength_0.50__threshold_1.01  h3_mesh_24  2.174793e-03
18  strength_0.50__threshold_1.01  h3_mesh_25  3.626964e-02
19  strength_0.50__threshold_1.01  h3_mesh_26  3.730636e-02
20  strength_0.50__threshold_1.01  h3_mesh_27  2.962244e-02
21  strength_0.50__threshold_1.01  h3_mesh_28  6.193040e-02
22  strength_0.50__threshold_1.01  h3_mesh_29  4.549510e-02
23  strength_0.50__threshold_1.01  h3_mesh_30  1.299194e-02
24  strength_0.50__threshold_1.01  h3_mesh_31  2.318221e-02
25  strength_0.50__threshold_1.01  h3_mesh_32  4.060352e-02
26  strength_0.50__threshold_1.01  h3_mesh_33  4.943965e-02
27  strength_0.50__threshold_1.01  h3_mesh_34  7.583486e-02
28  strength_0.50__threshold_1.01  h3_mesh_35  4.278780e-02
29  strength_0.50__threshold_1.01  h3_mesh_36  2.148679e-02

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1273.595992,-4.563633,pre,strength_0.50__threshold_0.70
1,2024-01-02,1289.206883,1285.105770,4.101113,pre,strength_0.50__threshold_0.70
2,2024-01-03,1305.904895,1296.184020,9.720876,pre,strength_0.50__threshold_0.70
3,2024-01-04,1316.002988,1304.821048,11.181939,pre,strength_0.50__threshold_0.70
4,2024-01-05,1338.300240,1320.194714,18.105526,pre,strength_0.50__threshold_0.70
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1447.251050,174.483902,post,strength_0.50__threshold_0.70
727,2025-12-28,1613.795981,1432.688811,181.107171,post,strength_0.50__threshold_0.70
728,2025-12-29,1541.604173,1373.404473,168.199700,post,strength_0.50__threshold_0.70
729,2025-12-30,1560.426800,1383.333363,177.093437,post,strength_0.50__threshold_0.70
730,2025-12-31,1570.726416,1391.082502,179.643914,post,strength_0.50__threshold_0.70

                      scenario_id donor_h3_id        weight
0   strength_0.50__threshold_0.70  h3_mesh_13  1.469560e-02
1   strength_0.50__threshold_0.70  h3_mesh_14  1.258508e-02
2   strength_0.50__threshold_0.70  h3_mesh_15  0.000000e+00
3   strength_0.50__threshold_0.70  h3_mesh_16  8.951726e-19
4   strength_0.50__threshold_0.70  h3_mesh_17  2.885077e-02
5   strength_0.50__threshold_0.70  h3_mesh_18  4.172011e-02
6   strength_0.50__threshold_0.70  h3_mesh_19  5.547472e-02
7   strength_0.50__threshold_0.70  h3_mesh_20  0.000000e+00
8   strength_0.50__threshold_0.70  h3_mesh_21  4.827261e-02
9   strength_0.50__threshold_0.70  h3_mesh_22  2.805422e-02
10  strength_0.50__threshold_0.70  h3_mesh_23  0.000000e+00
11  strength_0.50__threshold_0.70  h3_mesh_24  3.765360e-02
12  strength_0.50__threshold_0.70  h3_mesh_25  5.313692e-02
13  strength_0.50__threshold_0.70  h3_mesh_26  6.595899e-02
14  strength_0.50__threshold_0.70  h3_mesh_27  6.764886e-02
15  strength_0.50__threshold_0.70  h3_mesh_28  5.871389e-02
16  strength_0.50__threshold_0.70  h3_mesh_29  6.206895e-02
17  strength_0.50__threshold_0.70  h3_mesh_30  2.036424e-02
18  strength_0.50__threshold_0.70  h3_mesh_31  2.158219e-02
19  strength_0.50__threshold_0.70  h3_mesh_32  7.703022e-02
20  strength_0.50__threshold_0.70  h3_mesh_33  8.204537e-02
21  strength_0.50__threshold_0.70  h3_mesh_34  1.156156e-01
22  strength_0.50__threshold_0.70  h3_mesh_35  7.048754e-02
23  strength_0.50__threshold_0.70  h3_mesh_36  3.804049e-02

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1257.680963,11.351396,pre,strength_0.50__threshold_0.60
1,2024-01-02,1289.206883,1273.919311,15.287572,pre,strength_0.50__threshold_0.60
2,2024-01-03,1305.904895,1284.310272,21.594623,pre,strength_0.50__threshold_0.60
3,2024-01-04,1316.002988,1292.264617,23.738371,pre,strength_0.50__threshold_0.60
4,2024-01-05,1338.300240,1313.713389,24.586851,pre,strength_0.50__threshold_0.60
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1434.289958,187.444994,post,strength_0.50__threshold_0.60
727,2025-12-28,1613.795981,1416.912768,196.883213,post,strength_0.50__threshold_0.60
728,2025-12-29,1541.604173,1351.048768,190.555405,post,strength_0.50__threshold_0.60
729,2025-12-30,1560.426800,1369.050464,191.376336,post,strength_0.50__threshold_0.60
730,2025-12-31,1570.726416,1380.081552,190.644864,post,strength_0.50__threshold_0.60

                      scenario_id donor_h3_id        weight
0   strength_0.50__threshold_0.60  h3_mesh_13  4.298166e-17
1   strength_0.50__threshold_0.60  h3_mesh_14  3.147474e-02
2   strength_0.50__threshold_0.60  h3_mesh_15  0.000000e+00
3   strength_0.50__threshold_0.60  h3_mesh_16  3.967489e-18
4   strength_0.50__threshold_0.60  h3_mesh_17  4.888014e-02
5   strength_0.50__threshold_0.60  h3_mesh_18  1.384824e-01
6   strength_0.50__threshold_0.60  h3_mesh_19  1.206815e-01
7   strength_0.50__threshold_0.60  h3_mesh_20  1.578800e-18
8   strength_0.50__threshold_0.60  h3_mesh_21  1.894217e-02
9   strength_0.50__threshold_0.60  h3_mesh_22  1.402154e-02
10  strength_0.50__threshold_0.60  h3_mesh_23  0.000000e+00
11  strength_0.50__threshold_0.60  h3_mesh_24  1.065348e-02
12  strength_0.50__threshold_0.60  h3_mesh_25  3.572069e-02
13  strength_0.50__threshold_0.60  h3_mesh_26  4.118500e-02
14  strength_0.50__threshold_0.60  h3_mesh_27  1.775281e-01
15  strength_0.50__threshold_0.60  h3_mesh_28  2.315846e-17
16  strength_0.50__threshold_0.60  h3_mesh_29  2.121972e-01
17  strength_0.50__threshold_0.60  h3_mesh_30  1.502330e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1257.680963,11.351396,pre,strength_0.50__threshold_0.50
1,2024-01-02,1289.206883,1273.919311,15.287572,pre,strength_0.50__threshold_0.50
2,2024-01-03,1305.904895,1284.310272,21.594623,pre,strength_0.50__threshold_0.50
3,2024-01-04,1316.002988,1292.264617,23.738371,pre,strength_0.50__threshold_0.50
4,2024-01-05,1338.300240,1313.713389,24.586851,pre,strength_0.50__threshold_0.50
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1434.289958,187.444994,post,strength_0.50__threshold_0.50
727,2025-12-28,1613.795981,1416.912768,196.883213,post,strength_0.50__threshold_0.50
728,2025-12-29,1541.604173,1351.048768,190.555405,post,strength_0.50__threshold_0.50
729,2025-12-30,1560.426800,1369.050464,191.376336,post,strength_0.50__threshold_0.50
730,2025-12-31,1570.726416,1380.081552,190.644864,post,strength_0.50__threshold_0.50

                      scenario_id donor_h3_id        weight
0   strength_0.50__threshold_0.50  h3_mesh_13  4.298166e-17
1   strength_0.50__threshold_0.50  h3_mesh_14  3.147474e-02
2   strength_0.50__threshold_0.50  h3_mesh_15  0.000000e+00
3   strength_0.50__threshold_0.50  h3_mesh_16  3.967489e-18
4   strength_0.50__threshold_0.50  h3_mesh_17  4.888014e-02
5   strength_0.50__threshold_0.50  h3_mesh_18  1.384824e-01
6   strength_0.50__threshold_0.50  h3_mesh_19  1.206815e-01
7   strength_0.50__threshold_0.50  h3_mesh_20  1.578800e-18
8   strength_0.50__threshold_0.50  h3_mesh_21  1.894217e-02
9   strength_0.50__threshold_0.50  h3_mesh_22  1.402154e-02
10  strength_0.50__threshold_0.50  h3_mesh_23  0.000000e+00
11  strength_0.50__threshold_0.50  h3_mesh_24  1.065348e-02
12  strength_0.50__threshold_0.50  h3_mesh_25  3.572069e-02
13  strength_0.50__threshold_0.50  h3_mesh_26  4.118500e-02
14  strength_0.50__threshold_0.50  h3_mesh_27  1.775281e-01
15  strength_0.50__threshold_0.50  h3_mesh_28  2.315846e-17
16  strength_0.50__threshold_0.50  h3_mesh_29  2.121972e-01
17  strength_0.50__threshold_0.50  h3_mesh_30  1.502330e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1259.251455,9.780904,pre,strength_0.50__threshold_0.30
1,2024-01-02,1289.206883,1280.143575,9.063309,pre,strength_0.50__threshold_0.30
2,2024-01-03,1305.904895,1291.511263,14.393632,pre,strength_0.50__threshold_0.30
3,2024-01-04,1316.002988,1299.250608,16.752380,pre,strength_0.50__threshold_0.30
4,2024-01-05,1338.300240,1321.748798,16.551442,pre,strength_0.50__threshold_0.30
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1431.284370,190.450582,post,strength_0.50__threshold_0.30
727,2025-12-28,1613.795981,1413.723945,200.072037,post,strength_0.50__threshold_0.30
728,2025-12-29,1541.604173,1347.280542,194.323631,post,strength_0.50__threshold_0.30
729,2025-12-30,1560.426800,1364.173881,196.252919,post,strength_0.50__threshold_0.30
730,2025-12-31,1570.726416,1370.842141,199.884275,post,strength_0.50__threshold_0.30

                      scenario_id donor_h3_id        weight
0   strength_0.50__threshold_0.30  h3_mesh_19  1.290707e-01
1   strength_0.50__threshold_0.30  h3_mesh_20  0.000000e+00
2   strength_0.50__threshold_0.30  h3_mesh_21  2.732731e-02
3   strength_0.50__threshold_0.30  h3_mesh_22  1.512740e-02
4   strength_0.50__threshold_0.30  h3_mesh_23  1.430850e-17
5   strength_0.50__threshold_0.30  h3_mesh_24  4.357521e-02
6   strength_0.50__threshold_0.30  h3_mesh_25  4.312686e-02
7   strength_0.50__threshold_0.30  h3_mesh_26  4.343876e-02
8   strength_0.50__threshold_0.30  h3_mesh_27  2.388176e-01
9   strength_0.50__threshold_0.30  h3_mesh_28  0.000000e+00
10  strength_0.50__threshold_0.30  h3_mesh_29  2.579806e-01
11  strength_0.50__threshold_0.30  h3_mesh_30  2.015356e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1274.327739,-5.295380,pre,strength_1.00__threshold_1.01
1,2024-01-02,1289.206883,1286.982157,2.224727,pre,strength_1.00__threshold_1.01
2,2024-01-03,1305.904895,1298.944127,6.960768,pre,strength_1.00__threshold_1.01
3,2024-01-04,1316.002988,1310.357281,5.645707,pre,strength_1.00__threshold_1.01
4,2024-01-05,1338.300240,1323.250608,15.049632,pre,strength_1.00__threshold_1.01
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1513.735350,107.999603,post,strength_1.00__threshold_1.01
727,2025-12-28,1613.795981,1500.950661,112.845321,post,strength_1.00__threshold_1.01
728,2025-12-29,1541.604173,1442.293721,99.310452,post,strength_1.00__threshold_1.01
729,2025-12-30,1560.426800,1456.581850,103.844950,post,strength_1.00__threshold_1.01
730,2025-12-31,1570.726416,1456.587281,114.139135,post,strength_1.00__threshold_1.01

                      scenario_id donor_h3_id        weight
0   strength_1.00__threshold_1.01  h3_mesh_07  3.259500e-02
1   strength_1.00__threshold_1.01  h3_mesh_08  8.682807e-02
2   strength_1.00__threshold_1.01  h3_mesh_09  8.343769e-02
3   strength_1.00__threshold_1.01  h3_mesh_10  1.143291e-01
4   strength_1.00__threshold_1.01  h3_mesh_11  1.219556e-21
5   strength_1.00__threshold_1.01  h3_mesh_12  2.560679e-02
6   strength_1.00__threshold_1.01  h3_mesh_13  2.162857e-03
7   strength_1.00__threshold_1.01  h3_mesh_14  4.670705e-19
8   strength_1.00__threshold_1.01  h3_mesh_15  1.579440e-02
9   strength_1.00__threshold_1.01  h3_mesh_16  1.809885e-18
10  strength_1.00__threshold_1.01  h3_mesh_17  2.309727e-02
11  strength_1.00__threshold_1.01  h3_mesh_18  2.180228e-02
12  strength_1.00__threshold_1.01  h3_mesh_19  4.629121e-02
13  strength_1.00__threshold_1.01  h3_mesh_20  0.000000e+00
14  strength_1.00__threshold_1.01  h3_mesh_21  3.576652e-02
15  strength_1.00__threshold_1.01  h3_mesh_22  2.549932e-02
16  strength_1.00__threshold_1.01  h3_mesh_23  7.664013e-03
17  strength_1.00__threshold_1.01  h3_mesh_24  2.174793e-03
18  strength_1.00__threshold_1.01  h3_mesh_25  3.626964e-02
19  strength_1.00__threshold_1.01  h3_mesh_26  3.730636e-02
20  strength_1.00__threshold_1.01  h3_mesh_27  2.962244e-02
21  strength_1.00__threshold_1.01  h3_mesh_28  6.193040e-02
22  strength_1.00__threshold_1.01  h3_mesh_29  4.549510e-02
23  strength_1.00__threshold_1.01  h3_mesh_30  1.299194e-02
24  strength_1.00__threshold_1.01  h3_mesh_31  2.318221e-02
25  strength_1.00__threshold_1.01  h3_mesh_32  4.060352e-02
26  strength_1.00__threshold_1.01  h3_mesh_33  4.943965e-02
27  strength_1.00__threshold_1.01  h3_mesh_34  7.583486e-02
28  strength_1.00__threshold_1.01  h3_mesh_35  4.278780e-02
29  strength_1.00__threshold_1.01  h3_mesh_36  2.148679e-02

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1273.595992,-4.563633,pre,strength_1.00__threshold_0.70
1,2024-01-02,1289.206883,1285.105770,4.101113,pre,strength_1.00__threshold_0.70
2,2024-01-03,1305.904895,1296.184020,9.720876,pre,strength_1.00__threshold_0.70
3,2024-01-04,1316.002988,1304.821048,11.181939,pre,strength_1.00__threshold_0.70
4,2024-01-05,1338.300240,1320.194714,18.105526,pre,strength_1.00__threshold_0.70
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1492.911643,128.823309,post,strength_1.00__threshold_0.70
727,2025-12-28,1613.795981,1478.349404,135.446578,post,strength_1.00__threshold_0.70
728,2025-12-29,1541.604173,1419.065067,122.539107,post,strength_1.00__threshold_0.70
729,2025-12-30,1560.426800,1428.993957,131.432844,post,strength_1.00__threshold_0.70
730,2025-12-31,1570.726416,1436.743095,133.983321,post,strength_1.00__threshold_0.70

                      scenario_id donor_h3_id        weight
0   strength_1.00__threshold_0.70  h3_mesh_13  1.469560e-02
1   strength_1.00__threshold_0.70  h3_mesh_14  1.258508e-02
2   strength_1.00__threshold_0.70  h3_mesh_15  0.000000e+00
3   strength_1.00__threshold_0.70  h3_mesh_16  8.951726e-19
4   strength_1.00__threshold_0.70  h3_mesh_17  2.885077e-02
5   strength_1.00__threshold_0.70  h3_mesh_18  4.172011e-02
6   strength_1.00__threshold_0.70  h3_mesh_19  5.547472e-02
7   strength_1.00__threshold_0.70  h3_mesh_20  0.000000e+00
8   strength_1.00__threshold_0.70  h3_mesh_21  4.827261e-02
9   strength_1.00__threshold_0.70  h3_mesh_22  2.805422e-02
10  strength_1.00__threshold_0.70  h3_mesh_23  0.000000e+00
11  strength_1.00__threshold_0.70  h3_mesh_24  3.765360e-02
12  strength_1.00__threshold_0.70  h3_mesh_25  5.313692e-02
13  strength_1.00__threshold_0.70  h3_mesh_26  6.595899e-02
14  strength_1.00__threshold_0.70  h3_mesh_27  6.764886e-02
15  strength_1.00__threshold_0.70  h3_mesh_28  5.871389e-02
16  strength_1.00__threshold_0.70  h3_mesh_29  6.206895e-02
17  strength_1.00__threshold_0.70  h3_mesh_30  2.036424e-02
18  strength_1.00__threshold_0.70  h3_mesh_31  2.158219e-02
19  strength_1.00__threshold_0.70  h3_mesh_32  7.703022e-02
20  strength_1.00__threshold_0.70  h3_mesh_33  8.204537e-02
21  strength_1.00__threshold_0.70  h3_mesh_34  1.156156e-01
22  strength_1.00__threshold_0.70  h3_mesh_35  7.048754e-02
23  strength_1.00__threshold_0.70  h3_mesh_36  3.804049e-02

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1257.680963,11.351396,pre,strength_1.00__threshold_0.60
1,2024-01-02,1289.206883,1273.919311,15.287572,pre,strength_1.00__threshold_0.60
2,2024-01-03,1305.904895,1284.310272,21.594623,pre,strength_1.00__threshold_0.60
3,2024-01-04,1316.002988,1292.264617,23.738371,pre,strength_1.00__threshold_0.60
4,2024-01-05,1338.300240,1313.713389,24.586851,pre,strength_1.00__threshold_0.60
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1463.211626,158.523326,post,strength_1.00__threshold_0.60
727,2025-12-28,1613.795981,1445.834437,167.961545,post,strength_1.00__threshold_0.60
728,2025-12-29,1541.604173,1379.970436,161.633737,post,strength_1.00__threshold_0.60
729,2025-12-30,1560.426800,1397.972132,162.454668,post,strength_1.00__threshold_0.60
730,2025-12-31,1570.726416,1409.003221,161.723195,post,strength_1.00__threshold_0.60

                      scenario_id donor_h3_id        weight
0   strength_1.00__threshold_0.60  h3_mesh_13  4.298166e-17
1   strength_1.00__threshold_0.60  h3_mesh_14  3.147474e-02
2   strength_1.00__threshold_0.60  h3_mesh_15  0.000000e+00
3   strength_1.00__threshold_0.60  h3_mesh_16  3.967489e-18
4   strength_1.00__threshold_0.60  h3_mesh_17  4.888014e-02
5   strength_1.00__threshold_0.60  h3_mesh_18  1.384824e-01
6   strength_1.00__threshold_0.60  h3_mesh_19  1.206815e-01
7   strength_1.00__threshold_0.60  h3_mesh_20  1.578800e-18
8   strength_1.00__threshold_0.60  h3_mesh_21  1.894217e-02
9   strength_1.00__threshold_0.60  h3_mesh_22  1.402154e-02
10  strength_1.00__threshold_0.60  h3_mesh_23  0.000000e+00
11  strength_1.00__threshold_0.60  h3_mesh_24  1.065348e-02
12  strength_1.00__threshold_0.60  h3_mesh_25  3.572069e-02
13  strength_1.00__threshold_0.60  h3_mesh_26  4.118500e-02
14  strength_1.00__threshold_0.60  h3_mesh_27  1.775281e-01
15  strength_1.00__threshold_0.60  h3_mesh_28  2.315846e-17
16  strength_1.00__threshold_0.60  h3_mesh_29  2.121972e-01
17  strength_1.00__threshold_0.60  h3_mesh_30  1.502330e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1257.680963,11.351396,pre,strength_1.00__threshold_0.50
1,2024-01-02,1289.206883,1273.919311,15.287572,pre,strength_1.00__threshold_0.50
2,2024-01-03,1305.904895,1284.310272,21.594623,pre,strength_1.00__threshold_0.50
3,2024-01-04,1316.002988,1292.264617,23.738371,pre,strength_1.00__threshold_0.50
4,2024-01-05,1338.300240,1313.713389,24.586851,pre,strength_1.00__threshold_0.50
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1463.211626,158.523326,post,strength_1.00__threshold_0.50
727,2025-12-28,1613.795981,1445.834437,167.961545,post,strength_1.00__threshold_0.50
728,2025-12-29,1541.604173,1379.970436,161.633737,post,strength_1.00__threshold_0.50
729,2025-12-30,1560.426800,1397.972132,162.454668,post,strength_1.00__threshold_0.50
730,2025-12-31,1570.726416,1409.003221,161.723195,post,strength_1.00__threshold_0.50

                      scenario_id donor_h3_id        weight
0   strength_1.00__threshold_0.50  h3_mesh_13  4.298166e-17
1   strength_1.00__threshold_0.50  h3_mesh_14  3.147474e-02
2   strength_1.00__threshold_0.50  h3_mesh_15  0.000000e+00
3   strength_1.00__threshold_0.50  h3_mesh_16  3.967489e-18
4   strength_1.00__threshold_0.50  h3_mesh_17  4.888014e-02
5   strength_1.00__threshold_0.50  h3_mesh_18  1.384824e-01
6   strength_1.00__threshold_0.50  h3_mesh_19  1.206815e-01
7   strength_1.00__threshold_0.50  h3_mesh_20  1.578800e-18
8   strength_1.00__threshold_0.50  h3_mesh_21  1.894217e-02
9   strength_1.00__threshold_0.50  h3_mesh_22  1.402154e-02
10  strength_1.00__threshold_0.50  h3_mesh_23  0.000000e+00
11  strength_1.00__threshold_0.50  h3_mesh_24  1.065348e-02
12  strength_1.00__threshold_0.50  h3_mesh_25  3.572069e-02
13  strength_1.00__threshold_0.50  h3_mesh_26  4.118500e-02
14  strength_1.00__threshold_0.50  h3_mesh_27  1.775281e-01
15  strength_1.00__threshold_0.50  h3_mesh_28  2.315846e-17
16  strength_1.00__threshold_0.50  h3_mesh_29  2.121972e-01
17  strength_1.00__threshold_0.50  h3_mesh_30  1.502330e-01

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1259.251455,9.780904,pre,strength_1.00__threshold_0.30
1,2024-01-02,1289.206883,1280.143575,9.063309,pre,strength_1.00__threshold_0.30
2,2024-01-03,1305.904895,1291.511263,14.393632,pre,strength_1.00__threshold_0.30
3,2024-01-04,1316.002988,1299.250608,16.752380,pre,strength_1.00__threshold_0.30
4,2024-01-05,1338.300240,1321.748798,16.551442,pre,strength_1.00__threshold_0.30
...,...,...,...,...,...,...
726,2025-12-27,1621.734952,1454.467423,167.267529,post,strength_1.00__threshold_0.30
727,2025-12-28,1613.795981,1436.906998,176.888983,post,strength_1.00__threshold_0.30
728,2025-12-29,1541.604173,1370.463595,171.140578,post,strength_1.00__threshold_0.30
729,2025-12-30,1560.426800,1387.356935,173.069865,post,strength_1.00__threshold_0.30
730,2025-12-31,1570.726416,1394.025195,176.701221,post,strength_1.00__threshold_0.30

                      scenario_id donor_h3_id        weight
0   strength_1.00__threshold_0.30  h3_mesh_19  1.290707e-01
1   strength_1.00__threshold_0.30  h3_mesh_20  0.000000e+00
2   strength_1.00__threshold_0.30  h3_mesh_21  2.732731e-02
3   strength_1.00__threshold_0.30  h3_mesh_22  1.512740e-02
4   strength_1.00__threshold_0.30  h3_mesh_23  1.430850e-17
5   strength_1.00__threshold_0.30  h3_mesh_24  4.357521e-02
6   strength_1.00__threshold_0.30  h3_mesh_25  4.312686e-02
7   strength_1.00__threshold_0.30  h3_mesh_26  4.343876e-02
8   strength_1.00__threshold_0.30  h3_mesh_27  2.388176e-01
9   strength_1.00__threshold_0.30  h3_mesh_28  0.000000e+00
10  strength_1.00__threshold_0.30  h3_mesh_29  2.579806e-01
11  strength_1.00__threshold_0.30  h3_mesh_30  2.015356e-01

summary_df

,scenario_id,spillover_strength,exclusion_threshold,excluded_groups,donor_mesh_count,pre_rmspe,post_rmspe,post_pre_rmspe_ratio,mean_post_gap,true_direct_effect,estimation_error
0,strength_0.00__threshold_1.01,0.00,1.01,none,30,9.043986,222.525067,24.604755,222.308901,220.0,2.308901
1,strength_0.00__threshold_0.70,0.00,0.70,donor_group_1,24,9.991868,221.763193,22.194368,221.554586,220.0,1.554586
2,strength_0.00__threshold_0.60,0.00,0.60,donor_group_1|donor_group_5,18,12.067109,222.373184,18.428041,222.085552,220.0,2.085552
3,strength_0.00__threshold_0.50,0.00,0.50,donor_group_1|donor_group_5,18,12.067109,222.373184,18.428041,222.085552,220.0,2.085552
4,strength_0.00__threshold_0.30,0.00,0.30,donor_group_1|donor_group_2|donor_group_5,12,12.637605,223.162897,17.658638,222.816910,220.0,2.816910
5,strength_0.25__threshold_1.01,0.25,1.01,none,30,9.043986,193.730480,21.420917,193.482145,220.0,-26.517855
6,strength_0.25__threshold_0.70,0.25,0.70,donor_group_1,24,9.991868,198.956836,19.911876,198.724289,220.0,-21.275711
7,strength_0.25__threshold_0.60,0.25,0.60,donor_group_1|donor_group_5,18,12.067109,207.932355,17.231331,207.624718,220.0,-12.375282
8,strength_0.25__threshold_0.50,0.25,0.50,donor_group_1|donor_group_5,18,12.067109,207.932355,17.231331,207.624718,220.0,-12.375282
9,strength_0.25__threshold_0.30,0.25,0.30,donor_group_1|donor_group_2|donor_group_5,12,12.637605,211.590325,16.742913,211.225384,220.0,-8.774616
10,strength_0.50__threshold_1.01,0.50,1.01,none,30,9.043986,164.947130,18.238322,164.655390,220.0,-55.344610
11,strength_0.50__threshold_0.70,0.50,0.70,donor_group_1,24,9.991868,176.156680,17.630005,175.893993,220.0,-44.106007
12,strength_0.50__threshold_0.60,0.50,0.60,donor_group_1|donor_group_5,18,12.067109,193.494513,16.034869,193.163884,220.0,-26.836116
13,strength_0.50__threshold_0.50,0.50,0.50,donor_group_1|donor_group_5,18,12.067109,193.494513,16.034869,193.163884,220.0,-26.836116
14,strength_0.50__threshold_0.30,0.50,0.30,donor_group_1|donor_group_2|donor_group_5,12,12.637605,200.019948,15.827362,199.633857,220.0,-20.366143
15,strength_1.00__threshold_1.01,1.00,1.01,none,30,9.043986,107.450270,11.880853,107.001880,220.0,-112.998120
16,strength_1.00__threshold_0.70,1.00,0.70,donor_group_1,24,9.991868,130.587969,13.069425,130.233400,220.0,-89.766600
17,strength_1.00__threshold_0.60,1.00,0.60,donor_group_1|donor_group_5,18,12.067109,164.630939,13.642947,164.242216,220.0,-55.757784
18,strength_1.00__threshold_0.50,1.00,0.50,donor_group_1|donor_group_5,18,12.067109,164.630939,13.642947,164.242216,220.0,-55.757784
19,strength_1.00__threshold_0.30,1.00,0.30,donor_group_1|donor_group_2|donor_group_5,12,12.637605,176.887504,13.996916,176.450803,220.0,-43.549197

series_df series_df : 20シナリオ * 731日（閏年含む）/シナリオ = 14620行

,date,actual_treated_area,synthetic_treated_area,gap,period,scenario_id
0,2024-01-01,1269.032359,1274.327739,-5.295380,pre,strength_0.00__threshold_1.01
1,2024-01-02,1289.206883,1286.982157,2.224727,pre,strength_0.00__threshold_1.01
2,2024-01-03,1305.904895,1298.944127,6.960768,pre,strength_0.00__threshold_1.01
3,2024-01-04,1316.002988,1310.357281,5.645707,pre,strength_0.00__threshold_1.01
4,2024-01-05,1338.300240,1323.250608,15.049632,pre,strength_0.00__threshold_1.01
...,...,...,...,...,...,...
14615,2025-12-27,1621.734952,1454.467423,167.267529,post,strength_1.00__threshold_0.30
14616,2025-12-28,1613.795981,1436.906998,176.888983,post,strength_1.00__threshold_0.30
14617,2025-12-29,1541.604173,1370.463595,171.140578,post,strength_1.00__threshold_0.30
14618,2025-12-30,1560.426800,1387.356935,173.069865,post,strength_1.00__threshold_0.30
14619,2025-12-31,1570.726416,1394.025195,176.701221,post,strength_1.00__threshold_0.30

weights_df : 総行数は、20個の各シナリオで選ばれたドナーメッシュの数をすべて合計したもの

                       scenario_id donor_h3_id        weight
0    strength_0.00__threshold_1.01  h3_mesh_07  3.259500e-02
1    strength_0.00__threshold_1.01  h3_mesh_08  8.682807e-02
2    strength_0.00__threshold_1.01  h3_mesh_09  8.343769e-02
3    strength_0.00__threshold_1.01  h3_mesh_10  1.143291e-01
4    strength_0.00__threshold_1.01  h3_mesh_11  1.219556e-21
..                             ...         ...           ...
403  strength_1.00__threshold_0.30  h3_mesh_26  4.343876e-02
404  strength_1.00__threshold_0.30  h3_mesh_27  2.388176e-01
405  strength_1.00__threshold_0.30  h3_mesh_28  0.000000e+00
406  strength_1.00__threshold_0.30  h3_mesh_29  2.579806e-01
407  strength_1.00__threshold_0.30  h3_mesh_30  2.015356e-01

[408 rows x 3 columns]

,input_path,date_min,date_max,date_count,row_count,mesh_count,treated_mesh_count,donor_mesh_count,duplicate_date_h3_count,missing_value_count,true_direct_effect,spillover_formula
0,/content/drive/MyDrive/因果推論/h3_mesh_panel.csv,2024-01-01,2025-12-31,731,26316,36,6,30,0,0,220.0,strength * artificial_overlap_score * true_effect